### ISSUE TITLE
SUGGESTION: Catchall state for errors

### ISSUE THREAD

**Issue by utf** [Matgenix/jobflow-remote#111]
I've run into the case where I want to query for jobs that didn't finish. I don't care about the state they got to, I just want to find those that failed. Currently, I can do 2 separate queries:

```
jf job list --state FAILED
jf job list --state REMOTE_ERROR
```

But it might be nice to have a way to do this in one query.

**Comment by davidwaroquiers** [comment]
One point to make here is that the way to deal with these two kinds of error is different. So it could indeed be useful to have a shortcut just to know, but then in any case for a FAILED job, likely you will change something and make a restart of the job (i.e. restart from scratch), while for the REMOTE_ERROR, you'd retry to continue the process (e.g. vasp may have finished on the cluster, but the runner could not get back the files for some reason, e.g. no space left on the machine where the runner is being executed, you did some space and now you retry and it should hopefully work).

Also I don't know if the --state currently handles list of states, but this might be something possible and there could be a shortcut (e.g. ALL_ERRORS or ERRORS or something like that) that "expands" to FAILED+REMOTE_ERROR.

**Comment by utf** [comment]
Thanks for the thoughts. I guess I need to think more about what this option would be for. I think it can be useful to get an overview of the current state of jobs. However, I can imagine that if you have a large database with many failed jobs, this is potentially less useful.

As a side thought, I wonder whether an utility such as `jf job summarise` could be useful, which gives a high level overview of the state of the queue. E.g.
- Number of jobs running
- Number of jobs waiting to run
- Number of jobs failed
- Number of jobs completed in last 24 hours
- Number of jobs failed in last 24 hours

**Comment by gpetretto** [comment]
At the moment the code does not allow to query based on multiple states. 
The default option for typer list of arguments would be to have a query like this
```
jf job list --state FAILED --state REMOTE_ERROR
```
But then also all the lower level functions in JobController get a single state. So the change should be propagated through the various calls. 
If the query above is inconvenient it would also be possible to add a way to query for the all the failed jobs. Since the list of options available is based on the `JobState` enum, having something like 
```
jf job list --state ERRORS
```
would mean definining another Enum and having to deal with that. What about an additional filter option:
```
jf job list --error
```
Not sure which would be better for the user.

**Comment by utf** [comment]
I think adding a new state is probably more confusing as there are many states already. I like the option of `jf job list --error` personally.
