### ISSUE TITLE
Is there a way to visualize the workflow based on jobflow-remote info?

### ISSUE THREAD

**Issue by QuantumChemist** [Matgenix/jobflow-remote#149]
... and if not, would you mind if I add some code to generate a Mermaid flowchart based on jf job info (or similar)?

I know there is to_mermaid in jobflow that can visualize your Flow object but it doesn't contain the dynamic jobs.

I could think of making a Mermaid flowchart that can be output in the terminal (if that's possible at least) and as any kind of image format.

**Comment by davidwaroquiers** [comment]
You can look at the jf flow graph command. Not (yet) full flavored but still nice (mermaid and dash-cytoscape).

**Comment by QuantumChemist** [comment]
> You can look at the jf flow graph command. Not (yet) full flavored but still nice (mermaid and dash-cytoscape).

Cool thank you! I'll try that!

**Comment by QuantumChemist** [comment]
Do you have any idea how I could solve this problem?

```
(auto) certural@...:~$ jf flow graph -m f11725bd-595b-45ba-95cb-0f2a5dab4feb
The selected project is auto from config file /home/certural/.jfremote/auto.yaml
An Error occurred during the command execution: OperationFailure PlanExecutor error during aggregation :: caused by :: Total size of documents in jobs matching pipeline's $lookup 
stage exceeds 104857600 bytes, full error: {'ok': 0.0, 'errmsg': "PlanExecutor error during aggregation :: caused by :: Total size of documents in jobs matching pipeline's $lookup 
stage exceeds 104857600 bytes", 'code': 4568, 'codeName': 'Location4568'}

```

**Comment by gpetretto** [comment]
Hi, the error seems to come from the MongoDB query. That one fetches most of the data of the Jobs also from the jobs collection. Is the Flow very large?

**Comment by QuantumChemist** [comment]
> Hi, the error seems to come from the MongoDB query. That one fetches most of the data of the Jobs also from the jobs collection. Is the Flow very large?

Yes, it has 1055 jobs.

**Comment by gpetretto** [comment]
Hi @QuantumChemist,
the graph command (as well as some other commands) fetched more information than that actually needed. This was not a problem for relatively small Job documents and number of Jobs, but clearly is for your use case.
I made an update in this branch: https://github.com/Matgenix/jobflow-remote/tree/gp/minor_updates
Would you be available to test it to check if this solves your issue?

**Comment by QuantumChemist** [comment]
Hi @gpetretto !

sorry for the late reply. I was hit by a lot of side tasks that had to be done and didn't earlier get the time to look into this.
I think it worked. I cannot 100% check it right now, because I got a 4500 line output that is beyond good and evil for every mermaid diagram generator I know, even if I set the maxEdges to a way larger number. I'm thinking how I can shorten it to get a nice diagram. If you want and have time for it, you can check my output here: 
[mermaid.txt](https://github.com/user-attachments/files/16358752/mermaid.txt)


I just got the following error when executing the plot command:
`An Error occurred during the command execution: NetworkXException G is not planar.`

Thank you a lot for the code adjustment! 😃

**Comment by gpetretto** [comment]
Hi @QuantumChemist, no worries and thanks for testing this. 

If I undestand correctly, you get the mermaid text, but you also get the last error from networkx complaining that the graph is not planar. At the moment I am relying on a function in jobflow that [assumes the graph is planar](https://github.com/materialsproject/jobflow/blob/599c4453b18424cc42c15f07471d524f11e1f4a1/src/jobflow/utils/graph.py#L88). Maybe we should open a PR to update that. Do you happen to have an example where this error happens, but not with such a large number of nodes?

Concerning mermaid, I wonder if the generated text could be more efficient in terms of elements added. When I wrote the code I was more concerned to have it correct, rather than optimized. I did not think about very large workflows. 😄

**Comment by QuantumChemist** [comment]
Hi @gpetretto :)

yes, I get the mermaid text but also the error. Honestly, I'm still quite inexperienced with  mermaid, that I didn't know there are planar graphs 😅 
If you like, we can draft a PR for that and add non-planar graphs and also maybe make the generated text more efficient for large workflows.

I don't have an example but either our intern student or I can produce one. It might take a while though. The graph thing also doesn't hurry so much. It would just be a very nice addition for my paper.

**Comment by gpetretto** [comment]
Sorry, I think that both my previous message and that part of the code are a bit confusing. Even if you specify the `-m` option, the code still tries to plot the graph with networkX (as if you don't pass the `-m` option. Basically the `-m` adds the mermaid output instead of replacing it. It probably should not be like this...)
So there are two separate problems: 1) the mermaid output is too big. I am not sure if there is really something that can be done about it. 2) networkx does not like the graph generated and refuses to plot it, but this should be independent from mermaid.

BTW, I managed to generate the mermaid plot with your text file using mermaid-cli. Not sure if it is really useful though: 
[mermaid_plot.pdf](https://github.com/user-attachments/files/16372808/mermaid_plot.pdf)

**Comment by QuantumChemist** [comment]
aaahhh I see it's two different issues. So what would you suggest to do next? Do you think you will find some time to fix it or do you prefer me to do it?

Thanks for making the mermaid plot from my data. 😄  I think with this large number of jobs, I will opt to just plot a flow with fewer jobs and generate an exemplary graph instead of plotting the full, real flow

**Comment by gpetretto** [comment]
I changed the `graph` option so that when the `--mermaid` or `--dash` options are used the networkx plot is not generated. Seems more reasonable. 
I will not have a the chance for the next weeks to change the graph function in jobflow to switch to non planar graphs. Would you be available to fix that? (if you have the will and time)

**Comment by QuantumChemist** [comment]
In principle I have the will and at least on some weekends I also have the time. But this has no hurry for me actually. I will then start a PR once I get some time for it.
