### ISSUE TITLE
"Error executing jf project check --errors to connect to <cluster> (no additional info)"

### ISSUE THREAD

**Issue by soge8904** [Matgenix/jobflow-remote#208]
Hi,
I'm just starting to use jobflow-remote but I'm encountering an error when connecting to the supercomputer. 
I followed the setup instructions in the documentation and got to the point of running **project check --errors** but it throws me an error on the Worker, while Jobstore and Queue store seem to be setup correctly. This is the error I get:

> Errors:
> Worker perlmutter
> Command was executed but some error occurred.
> stdoud: bin/
> test

The only directory I have in my home directory is bin/. It doesn't show me a more detailed error output so I have no idea where to start in solving this.

I appreciate any help on things I could try to get more info about this issue or how it can be solved!

Thank you,
Sophie

**Comment by gpetretto** [comment]
Hi @soge8904,

indeed the error message was not clear enough and it has indeed been updated in the development version. I suppose you are using the currently released version. A new version should be released soon.
From what I see in your output, the check is failing because it expects that the output only contains the "test" string, while for some reason you also have an "ls" of your home directory. This could be due to something that is added to your .bashrc on the cluster or could be the cluster returning it on its own. This check is present because this could be a problem for jobflow-remote in interpreting the outputs of the commands. 
If this is something that you have control on and it is fine to remove, that should probably be the easiest solution. Otherwise there is a fix for that, but it is only available in the development version at the moment. You will need to install the "develop" branch from github and add the `sanitize_command: true` option to your worker in the configuration file. E.g.
```yaml
workers:
    perlmutter:
        scheduler_type: slurm
        work_dir: ....
        ....
        sanitize_command: true
```

Let me know if this helps you fixing the problem.

**Comment by soge8904** [comment]
Ah I see! 
I had a function in my .bashrc that would run `ls` every time `cd` was executed which was causing this!

Thank you for your fast and detailed response!

**Comment by gpetretto** [comment]
Thanks for the update. I will close this. Feel free to reopen if the issue comes up again.
