### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by marcodigennaro** [Matgenix/jobflow-remote#3]
After creating a test project, ```jf project check``` returns ```An Error occurred during the command execution: KeyError 'type'```
We have tried to explicitly insert the mongostore as and as_dict() into the test.yaml file but we find inconsistent responses. Please check the attachments.
 
![Screenshot 2023-06-19 at 11 10 25](https://github.com/Matgenix/jobflow-remote/assets/21054239/324b8d66-4367-47d8-80ab-61954a14ed92)
![Screenshot 2023-06-19 at 11 26 13](https://github.com/Matgenix/jobflow-remote/assets/21054239/a919351f-153a-4b46-9dd0-f20974375a79)

**Comment by gpetretto** [comment]
Hi @marcodigennaro, thanks for reporting this. First a quick check. Which version of jobflow is installed? If it is the one installed with pip it may miss a bug fix. If that is the case, can you try again using the latest development version form https://github.com/materialsproject/jobflow? If is already the latest development version, can you send me an anonimized version of the config file?

**Comment by marcodigennaro** [comment]
it's the develop branch from github

**Comment by davidwaroquiers** [comment]
For jobflow-remote, it's the develop branch, but jobflow itself is the one from pypi.

**Comment by gpetretto** [comment]
Then it is missing your fix: https://github.com/materialsproject/jobflow/pull/331. I checked with Marco's project file and indeed I don't have that error. Admittedly I thought it would have worked even without it, but I have the latest version of jobflow in my test environment, so I did not realize that there was an issue.  
Since the fix is already in place in jobflow I don't think it is worth changing jobflow-remote, but rather starting using the most recent version of jobfow. 
@marcodigennaro can you try that?   
@utf do you think it could be a good time to have a new jobflow release?

**Comment by marcodigennaro** [comment]
I installed jobflow from git (main branch) and it works indeed
