### ISSUE TITLE
.jfremote yaml test unsensitive to port change

### ISSUE THREAD

**Issue by marcodigennaro** [Matgenix/jobflow-remote#4]
I have created a new db (KUBAS) on my previously running mongodb instance (note port is 27018).

![Screenshot 2023-06-19 at 16 35 36](https://github.com/Matgenix/jobflow-remote/assets/21054239/61728eaf-fb06-4b40-bb24-92e41b510a7c)

I have inserted the newly freshly created db+password in the ~/.jfremote/TEST.yaml file and I can't get ```jf admin remote``` working:
![image](https://github.com/Matgenix/jobflow-remote/assets/21054239/af10b354-9dd2-4f26-ad31-1c2da79904fa)

Note that between the two lines I changed the port in ```~/.jfremote/TEST.yaml``` from 27018 to 27017. 
![Screenshot 2023-06-19 at 16 40 11](https://github.com/Matgenix/jobflow-remote/assets/21054239/d7276b5a-e866-4304-915e-98adfc0629f6)

**Comment by gpetretto** [comment]
I think that it might be because the port 27018 is not set for the `queue` MongoStore.  

One thing that could be helpful in this testing phase: if you run the command with `jf -fe admin reset` it should print the full stack trace of the error, and not just the error message. It might be helpful to identify the source of the error more easily.

**Comment by marcodigennaro** [comment]
Inserting the port under the ```queue``` key modified the output. Now I've got an authentication error though.
Note that I can successfully connect through:  ```mongo --port 27018 -u "mdi0316" -p "psw"```

**Comment by marcodigennaro** [comment]
In my previous running mongodb instance there was a lot of mambo jumbo to fix the connection to the remote cluster. I solved simply by restoring default values in mongodb.
