### ISSUE TITLE
Question about supported data types

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Matgenix/jobflow-remote#44]
Hi friends. What are the supported data types for dispatched functions in terms of the args/kwargs? Typical MSONable? I'm curious if passing a function as a keyword argument would be possible. **Disclaimer**: I haven't actually used jobflow-remote yet, so apologies if this is obvious once I do start to try it out.

Something like the following toy example (obviously one would never need to write it this way for such a simple example):

```python
# mymodule

def add(a: float, b: float) -> float:
    return a + b

def mult(a: float, b: float) -> float:
    return a * b
```

```python
from jobflow import job
from mymodule import add, mult

@job
def my_job(a: float, b: float, op: callable = add) -> float:
    return op(a, b)

my_job(a, b, op=mult)
```

**Comment by davidwaroquiers** [comment]
Hi @Andrew-S-Rosen 

Indeed I believe it won't work (not necessarily due to jobflow-remote). It would indeed be a good addition but I think it should be within jobflow itself (or maybe monty MSONable ? not sure if that would be so easy ?). Typical args and kwargs are currently indeed MSONable objects.

Regarding jobflow-remote itself, if you'd like to have a call to have a quick demo, don't hesitate to reach out :)

**Comment by utf** [comment]
There is already support for this in jobflow... I made callable functions msonable in monty in these PRs: 
- Builtin callables: https://github.com/materialsvirtuallab/monty/pull/251 
- General callables: https://github.com/materialsvirtuallab/monty/pull/239

**Comment by davidwaroquiers** [comment]
Nice! I wasn't aware of that (or maybe forgot). Then it should also work in jobflow-remote but we should probably test this specifically just to be sure.

**Comment by Andrew-S-Rosen** [comment]
This just made me so happy. Thank you both!! I had assumed it wasn't MSONable, but it looks like you already took care of that, @utf. Beautiful!!
