### ISSUE TITLE
Command line "jf project" when there is no project

### ISSUE THREAD

**Issue by davidwaroquiers** [Matgenix/jobflow-remote#5]
When there is no project defined in the .jfremote project, the "jf project" command does not work (and is not providing the help context).

I would also maybe provide the help together with the current project info maybe ? So that the user knows which project he is on and he  knows what else he can do. What do you think ?

**Comment by gpetretto** [comment]
I think we agreed that the `jf project` command would print the current available project instead of `jf project active`. If there is no project defined it tells that. So I would consider it working as expected.
You can still get the help for the project commands with `jf project -h`

The help is generated automatically by typer and I am not sure if there is a way to print the help even if something is executed. In a quick try I did not manage to. Even if it was possible I think that the information about the current project would be rather lost among the help messages. I also doubt the user would want to see them together, one usually wants one or the other.

I suppose that the options are:
1) `jf project` prints the selected project (as it is now)
2) `jf project` prints the help message, `jf project active` prints the active project (as it was before)
3) whichever `jf` command gets executed it first prints the message with current active project (or the message that no project is active). But not if the help is printed

**Comment by davidwaroquiers** [comment]
@gpetretto I think we decided about this and we can close this issue. Feel free to keep it open if you think it should stay open.
