### ISSUE TITLE
jf job list shows errors randomly

### ISSUE THREAD

**Issue by naik-aakash** [Matgenix/jobflow-remote#63]
Hi @gpetretto ,

I encounter this error from time to time on using `jf job list`. Does it have anything to do with setup ? But all jobs seem to run fine and results are stored in the Mongostore as expected.  And after a while I also get desired output printed from this command.

Not sure it is something that is still worked on ?

![image](https://github.com/Matgenix/jobflow-remote/assets/91958822/d80b2661-56e2-46b0-ad9d-9f1bfbe2ac04)

**Comment by gpetretto** [comment]
Hi @naik-aakash,

this is indeed a known issue coming from qtoolkit, and it has already been addressed there. If you wish you can pull the latest development version here https://github.com/Matgenix/qtoolkit, otherwise we will make a new release of qtk soon. In any case it is just an error coming from deserializing the data fetched from the DB, it will not impact the Flow execution.

**Comment by gpetretto** [comment]
Should be fixed with [QTK 0.1.2](https://github.com/Matgenix/qtoolkit/releases/tag/v0.1.2)

**Comment by naik-aakash** [comment]
Thanks @gpetretto !
