### ISSUE TITLE
Jobs with RESERVED state have datetime objects for `last_updated` field

### ISSUE THREAD

**Issue by ml-evs** [Matgenix/jobflow-remote#8]
And this breaks the CLI, which expects a string.

I have added a fix in #7 (described more there) that both sets the database field to a string, and also allows a string through the CLI for compatibility.

It's a shame FW uses isostrings rather than queryable MongoDB `$date`s...

**Comment by gpetretto** [comment]
Hi, I am bit surprised about this. Fireworks is quite inconsistent with the handling of the dates, but in general the workflows have these fields as actual Mongodb dates. Or at least they are in my old fireworks databases. I actually had to switch to the actual date because I encountered the opposite problem. When did you get the error?

**Comment by ml-evs** [comment]
Hard to say what actually triggered it, but during mine and @davidwaroquiers's attempts to get my jf runner working, some jobs got stuck in an "ONGOING" state but `jf job list` failed with the date/str error. Looking at my FW db, I can see a mix of dates and strings... see screenshot from the MongoDB GUI which emphasises this for the `updated_on` field.

![2023-07-12-153103_391x502_scrot](https://github.com/Matgenix/jobflow-remote/assets/7916000/eb93f7e0-7c19-4fac-8892-6f548997f7ef)


I assumed that https://github.com/Matgenix/jobflow-remote/pull/7/commits/ee4f0b7cb489411012729f6429a39cb95c35f900 would fix it, but as you say perhaps it should be the other way around.

**Comment by gpetretto** [comment]
It is indeed weird, since in my databases (both those with standard Fireworks workflows and those with jobflow-remote workflows) both `created_on` and `updated_on` are always real dates and not strings.  
I don't know where the difference could come from. In general it should not be an option which option is picked, when it comes to visualization (assuming both date and string cases are handled). The problem would come when filtering. Since I had only dates I limited the search by the use of real dates when building the query:
https://github.com/Matgenix/jobflow-remote/blob/a6f8915af25465144c623808932e75a15f02a0e7/src/jobflow_remote/jobs/jobcontroller.py#L169
(note that there is an issue, as the variable is called `start_date_str` because of a copy/paste, but it is not a string. I will fix this, depending on the chosen format)
However, if both dates and strings could be present, the search will end up failing in any case.  

At this point I don't know which would be the better option. @davidwaroquiers can you verify which format you have in your db? We can pick the format that appears more often and the problem should be solved as soon as we drop the fireworks dependence.

**Comment by ml-evs** [comment]
Closed by #7
